- id: rubocop
  name: rubocop
  description: Enforce the community Ruby Style Guide with RuboCop
  entry: rubocop
  language: ruby
  types: ['ruby']
  args: ['--autocorrect', '--force-exclusion', '-c', '.rubocop.yml']
