AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false
